source 'https://rubygems.org'

gemspec

gem 'addressable'
gem 'bundler'
gem 'image_size'
gem 'http'
gem 'kramdown'
gem 'mime-types'
gem 'minitest'
gem 'minitest-power_assert'
gem 'nokogiri'
gem 'path', github: 'eregon/path'
gem 'rake'
gem 'RedCloth'
gem 'rubypants'
gem 'rubytree'
gem 'sassc'
gem 'set_params', path: '~/Projects/set_params'
gem 'simple-builder', path: '~/Projects/simple-builder'
gem 'simple-pipeline', path: '~/Projects/simple-pipeline'